aws_region       = "us-east-1"
ec2_instance_type = "t2.micro"
key_name         = "nginx-server"
db_username      = "postgres"
db_password      = "admin123"
db_name          = "task_manager"
dockerhub_username = "pabloacker"
dockerhub_password = "1nc0rr3ct4_9700"